package com.jetbrains.edu.html.taskDescription

import com.jetbrains.edu.codeInsight.taskDescription.EduInCourseLinkPathCompletionTestBase
import com.jetbrains.edu.learning.courseFormat.DescriptionFormat

class EduHtmlInCourseLinkPathCompletionTest : EduInCourseLinkPathCompletionTestBase(DescriptionFormat.HTML)
