package com.jetbrains.edu.java.compatibility

import com.jetbrains.edu.learning.compatibility.CourseCompatibilityProviderTestBase
import com.jetbrains.edu.learning.compatibility.JCourseCompatibilityProvider

class JCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(JCourseCompatibilityProvider::class)