package com.jetbrains.edu.sql.java.compatibility

import com.jetbrains.edu.learning.compatibility.CourseCompatibilityProviderTestBase
import com.jetbrains.edu.learning.compatibility.SqlJCourseCompatibilityProvider

class SqlJCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(SqlJCourseCompatibilityProvider::class)
