package com.jetbrains.edu.sql.compatibility

import com.jetbrains.edu.learning.compatibility.CourseCompatibilityProviderTestBase
import com.jetbrains.edu.learning.compatibility.SqlCourseCompatibilityProvider

class SqlCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(SqlCourseCompatibilityProvider::class)
