package com.jetbrains.edu.markdown.taskDescription

import com.jetbrains.edu.codeInsight.taskDescription.EduToolWindowIdCompletionTestBase
import com.jetbrains.edu.learning.courseFormat.DescriptionFormat

class EduMarkdownToolWindowIdCompletionTest : EduToolWindowIdCompletionTestBase(DescriptionFormat.MD)
