package com.jetbrains.edu.cpp.compatibility

import com.jetbrains.edu.learning.compatibility.CourseCompatibilityProviderTestBase

class CppGTestCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(CppGTestCourseCompatibilityProvider::class)
class CppCatchCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(CppCatchCourseCompatibilityProvider::class)