package com.jetbrains.edu.sql.kotlin.compatibility

import com.jetbrains.edu.learning.compatibility.CourseCompatibilityProviderTestBase
import com.jetbrains.edu.learning.compatibility.SqlKtCourseCompatibilityProvider

class SqlKtCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(SqlKtCourseCompatibilityProvider::class)
